@extends('layouts.apps')

@push('header_script')
        <title>Sportify.id - Sumber Terbaik untuk Berita, Tinjauan, dan Analisis Olahraga</title>
        <meta name="title" content="Sportify.id - Sumber Terbaik untuk Berita, Tinjauan, dan Analisis Olahraga" />
        <meta name="description" content="Kunjungi Sportify.id untuk memperoleh informasi terbaru tentang olahraga dan untuk membaca berita, artikel, dan analisis terkait olahraga dari para ahli di bidangnya." />
        <meta name="keywords" content="olahraga, berita olahraga, informasi olahraga, sportify.id, media olahraga"/>
        <meta content="{{ URL::to('/') }}" itemprop="url" />
        <meta name="thumbnailUrl" content="{{ asset('assets/images/burger-black.svg') }}" />
        <!-- S:fb meta -->
        <meta property="og:type" content="website" />
        <meta property="og:image" content="{{ asset('assets/images/burger-black.svg') }}" />
        <meta property="og:title" content="Sportify.id - Sumber Terbaik untuk Berita, Tinjauan, dan Analisis Olahraga" />
        <meta property="og:description" content="Kunjungi Sportify.id untuk memperoleh informasi terbaru tentang olahraga dan untuk membaca berita, artikel, dan analisis terkait olahraga dari para ahli di bidangnya." />
        <meta property="og:url" content="{{ URL::to('/') }}" />
        <meta property="og:site_name" content="Sportify.id" />
        <meta property="fb:app_id" content="" />
        <!-- e:fb meta -->

        <!-- S:tweeter card -->
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="{{ URL::to('/') }}" />
        <meta name="twitter:creator" content="Sportify.id">
        <meta name="twitter:title" content="Sportify.id - Sumber Terbaik untuk Berita, Tinjauan, dan Analisis Olahraga" />
        <meta name="twitter:description" content="Kunjungi Sportify.id untuk memperoleh informasi terbaru tentang olahraga dan untuk membaca berita, artikel, dan analisis terkait olahraga dari para ahli di bidangnya." />
        <meta name="twitter:image" content="{{ asset('assets/images/burger-black.svg') }}" />
        <!-- E:tweeter card -->

        <meta name="content_location" content="Indonesia" />
        <meta name="content_author_id" content="sportify.id" />
        <meta name="content_author" content="sportify.id" />
        <meta name="content_editor_id" content="sportify.id" />
        <meta name="content_editor" content="sportify.id" />
        {{--        
        <meta name="content_type" content="singlepagenews" />
        <meta name="content_source" content="" />
        <meta name="content_tag" content="" />
        <meta name="content_tags" content="" />
        <meta name="content_total_words" content="" />
        <meta name="subscription" content="" /> --}}
@endpush

@section('content')

    <section class="section-top">
        <div class="area-title">
            <div class="container">
                <div class="col-12">
                    <h1>Terms of Services</h1>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="col-12">
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;padding:0cm 0cm 0cm 0cm;'>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;">Kebijakan Data Pribadi</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;">Sportify.id</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kompas Gramedia Group of Media atau dikenal dengan nama Sportify.id merupakan lini usaha yang berada dalam Kompas Gramedia Group dan perseroan lain yang terkait secara kepemilikan dengan Kompas Gramedia Group.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Sportify.id berkomitmen untuk melindungi data pribadi pelanggan, pengunjung, vendor, mitra, dan banyak pemilik kepentingan terkait lainnya. Oleh karena itu, dalam Kebijakan Data Pribadi ini, Kami mempertimbangkan aspek penerapan teknologi, sumber daya manusia, metode dan mengacu pada hukum yang berlaku di Indonesia, seperti Peraturan Menteri dan peraturan perundang-undangan lainnya yang terkait.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kebijakan Data Pribadi dalam halaman ini membantu Anda memahami bagaimana Sportify.id mengumpulkan, alasan Kami mengumpulkannya, mengolah, menganalisa, menyimpan, menggunakan, mengungkapkan, memberikan, mendistribusi, merevisi atau mengubah dan/atau memusnahkan Data Pribadi Anda yang dapat diidentifikasi dan diperoleh sehubungan dengan penggunaan Layanan.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">A. DEFINISI</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sportify.id/Kami berarti Kompas Gramedia Group of Media yang bergerak di berbagai bidang bisnis media, seperti Televisi, Radio, Percetakan, Digital dan bisnis area media lainnya.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Afiliasi berarti anak usaha dari dan/atau pihak di bawah kendali Kompas Gramedia Group of Media dan/atau Kompas Gramedia Group.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Layanan / layanan berarti setiap jasa dan/atau produk dan/atau kegiatan maupun layanan lainnya dalam bentuk apapun yang Kami berikan/selenggarakan baik yang Kami berikan/selenggarakan melalui Portal maupun tanpa melalui Portal (seperti event dan sebagainya).</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Portal berarti setiap aplikasi perangkat lunak dan/atau setiap situs-web dan/atau setiap bentuk platform digital lainnya baik yang sudah ada maupun akan ada di masa yang akan mendatang, yang Kami dan/atau Afiliasi Kami kembangkan dan operasikan sehingga Layanan Kami dapat diakses oleh Anda.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Pelanggan/Pengguna/Anda/Diri Sendiri adalah setiap pihak yang menggunakan dan/atau mengakses dan/atau turut serta pada Layanan Kami baik melalui Portal maupun tidak melalui Portal, serta baik yang sudah terdaftar pada Portal maupun yang belum terdaftar dalam Portal.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Data Pribadi / data berarti data atau informasi mengenai diri Anda yang Kami peroleh melalui penggunaan/interaksi Portal dan/atau layanan oleh Anda baik yang dapat diidentifikasi secara pribadi maupun yang belum diidentifikasi secara pribadi termasuk namun tidak terbatas seperti nama, alamat, tanggal lahir, tempat kelahiran, pekerjaan, tempat bekerja, identitas pribadi, dokumen identitas lainnya, nomor telepon, alamat surel, dan informasi lainnya yang dapat mengidentifikasi Anda sebagai pengguna.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Ketentuan Penggunaan berarti standar prosedur operasional atau ketentuan-ketentuan lainnya sehubungan dengan akses/penggunaan setiap Portal atau Layanan yang disediakan oleh Kami dan/atau Afiliasinya, yang dapat diubah dan diperbarui dari waktu ke waktu oleh Kami dan/atau Afiliasi.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">B. RUANG LINGKUP</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kebijakan Data Pribadi ini berlaku untuk semua Data Pribadi di seluruh Layanan Kami dan/atau mitra bisnis Kami (vendor, mitra, dan pemangku kepentingan lainnya). Mohon lihat berbagai produk dan anak usaha yang merupakan Afiliasi dari Kami di sini:</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: decimal;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">https://sportify.id</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Setiap penambahan suatu produk/layanan yang akan datang di kemudian hari merupakan produk/ layanan yang diakui oleh Kami, maka secara serta-merta mengikuti Kebijakan Data Pribadi ini. Dalam hal pembuktian tersebut, Kami tidak berkewajiban untuk menunjukan dokumen perusahaan Kami, namun Kami dapat menunjukan dokumen pernyataan yang menyatakan bahwa setiap produk atau layanan tersebut adalah benar termasuk layanan Kami.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">C. TUJUAN</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami mengumpulkan, mengolah, menggunakan dan memberikan Data Pribadi Anda termasuk kepada Afiliasi dan/atau pihak ketiga/mitra Kami, untuk tujuan berikut:</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: decimal;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk memberikan dukungan atau informasi lainnya;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami dapat menggunakan Data Pribadi Anda untuk memberikan dukungan atau informasi lain yang terkait dengan riwayat penggunaan yang telah dilakukan Pelanggan, termasuk namun tidak terbatas seperti keluhan Pelanggan, panggilan Pelanggan, konfirmasi Pelanggan yang terkait dengan layanan Kami.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk memberikan informasi mengenai produk atau informasi terkini;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami dapat menggunakan Data Pribadi Anda untuk memberikan pemberitahuan tentang penerbitan produk baru, pengembangan produk, penargetan ulang, promosi, penawaran yang dipersonalisasi, berlangganan, partisipasi acara, atau informasi yang mungkin Anda perlukan. Informasi ini tidak hanya terbatas pada produk/jasa dari layanan Kami baik yang pernah digunakan maupun belum pernah digunakan, tetapi juga produk/jasa Afiliasi atau mitra Kami yang sesuai dengan kebutuhan Anda. Kami dapat menggunakan Data Pribadi Anda dan catatan transaksi Anda untuk menganalisis perilaku Anda dan menggunakannya untuk memberikan informasi mengenai Layanan Kami dan/atau produk/jasa tersebut.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Menganalisis perilaku Pelanggan untuk memberikan pengalaman, pelayanan dan informasi yang lebih baik dan sesuai;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami menggunakan Data Pribadi Anda dari interaksi Anda dengan layanan Kami untuk menganalisis minat dan pola perilaku Anda sehingga Kami dapat memberikan pengalaman, pelayanan, promosi dan informasi yang lebih baik dan sesuai untuk kebutuhan Anda.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk menginformasikan manfaat, program, dan kesempatan yang Kami berikan kepada Anda;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami dan/atau Afiliasi dapat mengkomunikasikan kepada Anda mengenai manfaat, program, dan kesempatan yang dapat diberikan terkait Layanan Kami dan/atau Afiliasi Kami.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk berhubungan dengan pihak ketiga/mitra Kami;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami dapat membagikan Data Pribadi Anda kepada pihak ketiga/mitra Kami yang berkaitan dengan kepentingan usaha Kami dan/atau Afiliasi dan/atau kebutuhan Kami lainnya termasuk namun tidak terbatas berkaitan dengan penyelesaian transaksi atas Layanan Kami dan/atau Afiliasi Kami yang bersentuhan dengan Pelanggan, berkaitan dengan kebutuhan bagi pihak ketiga/mitra Kami dan/atau Afiliasi Kami, dan kebutuhan-kebutuhan lainnya. Kami juga membagikan Data Pribadi Anda dengan pihak ketiga/mitra Kami yang menurut kami dapat memberikan konten, produk-produk, atau layanan mereka yang sesuai dengan minat Anda. Kami memastikan bahwa pihak ketiga/mitra Kami ini dipilih dengan kehati-hatian dan berkewajiban untuk menjaga Data Pribadi Anda tetap aman.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk melindungi konten dan Layanan Kami;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami menggunakan Data Pribadi untuk mencegah aktifitas ilegal yang potensial dan menegakkan Ketentuan Penggunaan . Kami juga menggunakan bermacam-macam sistem teknologi untuk mendeteksi aktifitas yang tidak lazim untuk penyalahgunaan, seperti spam, plagiarisme, pembajakan dan sebagainya.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Untuk mendapatkan saran dan masukan dari Anda dari waktu ke waktu;</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami dapat meminta Pelanggan untuk memberikan saran-saran, agar produk/Layanan lebih sesuai dengan yang Pelanggan butuhkan dan minati (sebagai contoh lewat survei, riset atas penggunaan, diskusi kelompok).</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Semua pelaksanaan isi dalam huruf C ini Kami lakukan dalam lingkup teritori/wilayah di seluruh Dunia.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:16px;font-family:Roboto;">&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:16px;font-family:Roboto;">&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:16px;font-family:Roboto;">&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">D. DATA YANG KAMI KUMPULKAN</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Kami mengumpulkan beberapa Data Pribadi yang secara langsung disediakan oleh Anda sebagai berikut:</span>
                        <ol style="list-style-type: lower-alpha;">
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Nama</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi kontak (telepon, surel)</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tanggal lahir</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tempat lahir</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Demografi: jenis kelamin, pekerjaan,</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi identifikasi pribadi (KTP, SIM, Paspor, dan identifikasi pribadi lainnya)</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi kontak darurat</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi profil media sosial</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi pendidikan dan pekerjaan</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi hal (-hal) yang ada minati</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi lain dari Anda, yang diunggah atau diberikan kepada Kami.</span></li>
                        </ol>
                    </li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Kami juga mengumpulkan beberapa informasi lainnya ketika Anda menggunakan Portal dan/atau layanan Kami yaitu :</span>
                        <ol style="list-style-type: lower-alpha;">
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi tentang perangkat(-perangkat) yang Anda gunakan</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi tentang penggunaan layanan</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Cookies.</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Data otentikasi</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi lokasi</span></li>
                        </ol>
                    </li>
                </ol>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">f. Data yang telah direkam melalui salah satu layanan Afiliasi juga akan digunakan untuk meningkatkan pengalaman Pelanggan di semua lini bisnis Kami dan Afiliasi.</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:56px;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Cookies yang dimaksud huruf c di atas adalah file teks kecil yang dikirim ke dan disimpan di komputer, ponsel pintar atau perangkat lain untuk mengakses internet, setiap kali Anda menggunakan Layanan Kami melalui Portal. Cookies berguna karena memungkinkan Portal mengenali perangkat pengguna</span></li>
                    </ol>
                </div>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Cookies membantu kami mempersonalisasi Portal dan memenuhi minat serta keinginan Pengguna. Kami menggunakan cookies untuk melindungi privasi Anda. Portal kami tidak menggunakan cookies untuk mengumpulkan informasi pribadi dari perangkat Anda. Kami tidak pernah menyimpan kata sandi atau data sensitif yang serupa dalam cookies</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami menggunakan &apos;analytics&apos; cookies untuk membantu menganalisis bagaimana pengguna mengakses Portal. Dengan menunjukkan bagaimana dan kapan pengguna menggunakan Portal, cookies membantu kami dalam mencari tahu halaman Portal mana yang populer dan mana yang tidak, dan bagaimana kami dapat memperbaiki Portal untuk Anda. Kami menggunakan cookies &apos;analisis&apos; di Portal sehingga dengan demikian, Kami hanya membagikan informasi cookies ini kepada pihak ketiga/mitra Kami yakni dalam format agregat dan anonimus (keseluruhan) serta tidak ada informasi yang bersifat pribadi.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Bagaimana Anda bisa mengatur cookies Anda? Browser kebanyakan komputer, ponsel pintar, dan perangkat berkemampuan web lainnya biasanya disiapkan untuk menerima cookies. Anda memiliki pilihan untuk mengontrol penerimaan cookies sendiri dan, jika Anda mau, Anda dapat memblokir sepenuhnya dengan mengkonfigurasi browser Internet Anda. Silakan lihat dokumentasi untuk browser Anda untuk mengubah preferensi Anda terkait cookies ini.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Harap diingat bahwa cookies digunakan untuk mengaktifkan dan memperbaiki fungsi tertentu pada Portal. Jika Anda memilih untuk menonaktifkan cookies tertentu, kemungkinan akan mempengaruhi cara kerja Portal kami.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">E. DATA YANG TIDAK KAMI KUMPULKAN</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami sangat menghargai kerahasian data Anda, oleh karena itu, Kami tidak mengumpulkan data-data berupa konten apapun dari album foto, komunikasi aplikasi pesan singkat (app messenger), dan informasi kontak/phonebook yang terkandung dalam perangkat anda.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">F. KEAMANAN</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Kerahasiaan informasi dan Data Pribadi Anda menjadi perhatian utama bagi Kami. Kami melakukan usaha dan prosedur terbaik untuk melindungi serta menjamin Data Pribadi dan Kami secara berkala melakukan evaluasi secara internal untuk meningkatkan keamanan sehingga Data Pribadi Anda aman dari gangguan pihak tanpa izin. Kami memastikan bahwa Data Pribadi yang Kami peroleh berada dalam bentuk data yang terenkripsi baik di dalam proses transmisi maupun penyimpanan di dalam server. Namun bagaimanapun, kami tidak dapat menjamin sepenuhnya bahwa sistem Kami tidak dapat ditembus oleh virus, malware, dan gangguan dari pihak tanpa izin.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Pengguna bertanggung jawab untuk selalu menjaga kerahasiaan data informasi yang ada dalam Portal maupun sehubungan dengan penggunaan Layanan, termasuk namun tidak terbatas pada kerahasiaan sandi yang Pengguna gunakan untuk mengakses akun di Portal Sportify.id. Mohon untuk tidak mengungkapkan dan membagikan Data Pribadi Anda, termasuk kata sandi akun Anda kepada siapapun dan tetap menjaga keamanan perangkat Anda. Kami tidak bertanggung jawab apabila Anda mengalami kerugian yang disebabkan oleh kelalaian Anda dalam menjaga kerahasiaan data informasi sehubungan dengan penggunaan Layanan maupun terhadap akun Anda di Portal, dan dengan ini Anda membebaskan Kami, direksi, dewan komisaris, karyawan, agen, dan/atau Afiliasi Kami, dari setiap tuntutan, gugatan, ganti rugi, dan/atau klaim yang Pengguna ajukan sehubungan dengan penggunaan dan/atau akses yang tidak sah terhadap akun Anda.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">G. IKLAN</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Iklan yang muncul pada Portal mungkin dikirim ke Anda oleh mitra kami, yang mungkin menerapkan cookies. Cookies ini memungkinkan server pada masing-masing iklan mengenali perangkat Pengguna setiap kali mereka mengirimkan iklan online untuk mengumpulkan data non-pribadi tentang Pengguna atau orang lain yang menggunakan perangkat dari Pengguna.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Ketika Anda menggunakan Portal Kami, ada kemungkinan muncul iklan tertentu yang mana adalah produk dari mitra kami. Mitra kami, sebagai vendor pihak ketiga, menggunakan cookies untuk menayangkan iklan di Portal Kami</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">H. KETENTUAN TERHADAP ANAK DI BAWAH UMUR</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Setiap pembuatan akun Portal dan/atau pendaftaran atas Layanan Sportify.id dan/atau Afiliasinya dilarang dilakukan oleh anak-anak di bawah usia 18 (delapan belas) tahun atau dibawah usia yang ditentukan peraturan perundang-undangan sehingga atas hal-hal tersebut wajib diwakili oleh orang tua atau walinya yang sah secara hukum.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Setiap pembuatan akun Portal dan/atau pendaftaran atas Layanan yang memang memiliki segmentasi untuk anak-anak di bawah umur tetap harus diwakili oleh orang tua dan/atau walinya yang sah secara hukum.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Setiap penggunaan Layanan yang memang memiliki segmentasi untuk anak-anak di bawah umur tetap harus dalam pengawasan serta persetujuan orang tua dan/atau walinya yang sah secara hukum.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Jika terdapat anak di bawah umur yang yang telah menyediakan Data Pribadi tanpa diwakili orang tua atau walinya yang sah secara hukum, maka orang tua atau wali harus menghubungi Sportify.id (lihat Bagian O) untuk mengajukan penghapusan Data Pribadi yang masuk dalam kategori &ldquo;data yang tidak relevan&rdquo; dan berhenti menggunakan akun Portal dan/atau Layanan tersebut (bila Layanan dan/atau Portal yang dimaksud tidak untuk segmentasi anak-anak di bawah umur).</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami tidak dapat membedakan secara langsung mengenai usia seseorang saat pembuatan akun Portal dan/atau penggunaan/pendaftaran atas Layanan Kami melalui Portal. Pelanggan wajib membebaskan Kami, Afiliasi dan/atau setiap pihak ketiga/mitra kami dari setiap klaim, gugatan dan/atau tuntutan yang timbul akibat Pelanggan melanggar ketentuan dalam huruf H ini serta Pelanggan wajib bertanggung jawab penuh setiap klaim, gugatan dan/atau tuntutan tersebut.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">I. INFORMASI TEKNIS DAN PERATURAN</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Data yang bersifat pribadi Pengguna: Kami mengumpulkan Data Pribadi dari Pengguna melalui berbagai cara, termasuk namun tidak terbatas pada, ketika Pengguna mengunjungi Portal, menggunakan fitur, mengakses konten yang kami sediakan dalam Portal, ketika mendaftar sebagai Pengguna, ketika Pengguna menggunakan layanan dan sebagainya. Pengguna juga dapat diminta memberikan data, antara lain, alamat surel, alamat rumah/kantor, nomor telepon dan informasi lainnya yang dibutuhkan.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Data yang bersifat non-pribadi Pengguna: Kami dapat mengumpulkan data non-pribadi Pengguna ketika mereka berinteraksi dengan Portal dan/atau layanan Kami. Setiap data non-personal termasuk namun tidak terbatas pada nama browser, tipe computer, perangkat telepon, atau informasi lainnya berkaitan dengan cara Pengguna terhubung dengan Portal kami, seperti system operasi, layanan internet, sosial media, dan informasi terkait lainnya.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Dalam hal ketika Anda memilih untuk menautkan akun media sosial atau akun Anda yang terkait dengan layanan pihak ketiga lainnya ke Layanan Kami dan/atau Portal, maka Anda mungkin meminta pihak ketiga untuk mengirimkan informasi tertentu kepada Kami dari akun media sosial atau akun layanan tersebut dan Anda mengijinkan Kami untuk mengumpulkan, menyimpan, dan menggunakan apa yang mereka kirimkan kepada Kami sesuai dengan yang dijelaskan dalam Kebijakan Data Pribadi ini.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Logging Practices.</span></li>
                </ol>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kami secara otomatis merekam alamat Internet Protocol (IP) dari Pengguna (web-based application) dan sesi dari pengguna (mobile application). Kami juga merekam beberapa material-material untuk mengindentifikasi pengguna atas Portal, termasuk:</span></p>
                <ul style="list-style-type: disc;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tipe/versi dari <em>browser</em>/perangkat&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sistem operasi yang digunakan&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tanggal dan waktu dari <em>server request</em>&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Lokasi (lintang dan bujur)&nbsp;</span></li>
                </ul>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Untuk aplikasi seluler, kami menggunakan bahan-bahan berikut untuk mengidentifikasi:&nbsp;</span></p>
                <ul style="list-style-type: disc;margin-left:92px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Brand dan/atau tipe/versi perangkat&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Perangkat IMEI&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sistem operasi yang digunakan&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tanggal dan waktu dari <em>server request</em>&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Lokasi (lintang dan bujur)&nbsp;</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Informasi lainnya yang disediakan oleh sistem operasi, browser maupun perangkat</span></li>
                </ul>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:66.0pt;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Identifikasi ini digunakan pada seluruh Layanan dan Portal Kami untuk memungkinkan dilakukan pemahaman atas data Pelanggan dari antar produk/Layanan. Ini menciptakan peluang yang lebih besar untuk Kami dalam memberikan pelayanan kepada Pelanggan yang lebih baik lagi.</span></p>
                <ol style="list-style-type: undefined;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">External links behavior: Beberapa Layanan Kami/Portal Kami mungkin tersambung/berisi tautan dengan situs/aplikasi lain yang dibuat dan dikelola oleh pihak lain/mitra kami. Ketika Anda masuk ke sebuah situs/aplikasi lain tersebut, maka perlu diketahui bahwa kami tidak bertanggung jawab atas pengumpulan data atau konten dari situs situs/aplikasi tersebut serta informasi apa pun yang mungkin mereka kumpulkan, walaupun nama atau logo kami mungkin dapat muncul di situs/aplikasi tersebut. Kami meminta Anda untuk waspada saat meninggalkan Portal kami dan membaca ketentuan privasi situs/aplikasi lain tersebut yang Anda kunjungi, karena kebijakan privasi situs/aplikasi lain tersebut tersebut mungkin berbeda dari kami</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Do Not Track (DNT): adalah sebuah self-regulatory initiative yang dirancang oleh industri periklanan daring untuk memberikan pilihan dalam jenis iklan yang mungkin mereka lihat dan pilih dari online behavioral ads yang disediakan oleh perusahaan-perusahaan yang berpartisipasi dalam hal ini. Kami tidak merespon atas DNT pada pengaturan browser Anda.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika Anda sudah tidak lagi menjadi Pengguna terdaftar atau menggunakan layanan Kami, Data Pribadi akan tetap Kami simpan sekurang-kurangnya 5 (lima) tahun sejak tanggal terakhir Anda menjadi Pengguna terdaftar atau sejak tanggal terakhir Anda menggunakan Layanan Kami/mengakses Portal atau selama jangka waktu lain yang sebagaimana diatur oleh hukum dan peraturan perundang-undangan yang berlaku di Indonesia.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Tanggapan atas permintaan hukum: Kami berhak untuk membagikan informasi Anda untuk menanggapi permintaan informasi Data Pribadi Anda dari otoritas Pemerintah dan/atau instansi yang berwenang atau disyaratkan oleh undang-undang.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">J. PERNYATAAN DAN PERSETUJUAN DATA PRIBADI</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Dengan menggunakan Portal dan/atau layanan Kami, berarti Anda menyatakan bahwa Anda telah membaca, mengerti dan setuju atas Kebijakan Data Pribadi ini beserta seluruh setiap perubahannya yang Kami lakukan dari waktu ke waktu dan setuju memperkenakan Kami untuk menggunakan, menerapkan, memproses, dan mengalihkan Data Pribadi Anda sebagaimana dinyatakan dalam Kebijakan Data Pribadi ini.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Anda juga menyatakan bahwa Anda sepakat dan menyetujui untuk membagikan atas seluruh informasi yang telah diberikan kepada Kami dan memberikan kepada Kami kewenangan untuk menghapus, menggunakan dan membagikan Data Pribadi Anda kepada Afiliasi Kami dan/atau pihak ketiga lainnya (seperti mitra kami, vendor dan lainnya) untuk mendukung Layanan dan/atau Portal Kami serta kegiatan usaha Kami dan Afiliasi Kami.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">K. PENCABUTAN PERSETUJUAN DAN PENGHAPUSAN DATA PRIBADI</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika Anda merupakan Pengguna yang terdaftar, Anda dapat meninjau, merevisi, dan memperbaiki Data Pribadi Anda melalui layanan pengaturan profil Pengguna pada Portal.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sportify.id hanya bertanggung jawab atas penghapusan dari data anda yang tersimpan di Akun Sportify.id anda.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sportify.id tidak bertanggung jawab terhadap data anda di luar dari data anda yang tersimpan di akun Sportify.id anda.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Anda dapat mencabut persetujuan Anda atas pengumpulan, penggunaan, dan keterbukaan Data Pribadi Anda dan/atau mengajukan penghapusan Data Pribadi Anda yang tersimpan dengan cara berikut :</span>
                        <ol style="list-style-type: decimal;">
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Bagi pengguna website, silahkan login kemudian akses menu profil</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Bagi pengguna aplikasi, pastikan anda sudah login kemudian akses halaman pengaturan.</span></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika pengguna ingin menghapus akun Sportify.id IDnya, namun tidak dapat mengakses akun tersebut berdasarkan kebijakan dari Sportify.id. Maka Pengguna tersebut bisa meminta penghapusan akun kepada Sportify.id dengan mengirimkan email ke alamat email&nbsp;</span><a href="mailto:info@sportify.id"><span style="font-family:Roboto;font-size:13.5pt;color:mediumblue;">info@sportify.id</span></a></li>
                            <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika penghapusan akun belum dapat dilakukan di apps Sportify.id, Pengguna dapat meminta penghapusan akun kepada Sportify.id dengan mengirimkan email ke&nbsp;</span><a href="mailto:info@sportify.id"><span style="font-family:Roboto;font-size:13.5pt;color:mediumblue;">info@sportify.id</span></a></li>
                        </ol>
                    </li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">L. KEBIJAKAN ALAMAT SUREL</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika Anda ingin berhenti untuk menerima newsletter pada surel Anda, silakan ikuti langkan berhenti berlangganan atau unsubscribe yang ada disudut bawah pada masing-masing Portal.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Kami dapat mengirimkan surel berupa undangan untuk berpartisipasi dalam survey pengguna, tanggapan sebagai pengunjung atau pengguna, serta layanan yang ada atau sedang dikembangkan.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika Anda berkomunikasi dengan Kami melalui surel, Kami dapat mempertahankan dan atau menyimpan isi dari pesan surel Anda, termasuk riwayat percakapan antara Kami dengan Anda dan alamat surel dan informasi yang Anda berikan selama komunikasi berlangsung.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Jika Anda ingin mengirimkan surel kepada Kami, disarankan Anda harus memahami bahwa informasi yang tercantum dalam surel tersebut tidak aman atau terenkripsi, sehingga memungkinkan terlihat oleh pihak lain. Dengan demikian, Anda diwajibkan berhati-hati saat mengirimkankan sesuatu yang bersifat rahasia ke surel Kami. Dalam hal ini, Kami tidak bertanggung jawab atas setiap surel yang Anda kirim kepada Kami dan tidak ada kewajiban Kami untuk memberikan bantuan atas setiap peristiwa yang merugikan Anda.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">M. PENYELESAIAN PERSELISIHAN DAN BAHASA</span></strong></p>
                <ol style="list-style-type: decimal;margin-left:56px;">
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Sportify.id dan Pengguna dengan ini setuju untuk berusaha sedapat mungkin mencapai penyelesaian secara musyawarah paling lama 30 (tiga puluh) hari kerja sejak salah satu pihak menerima surat tertulis dari pihak lainnya</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Apabila penyelesaian melalui musyawarah tersebut gagal mencapai kata mufakat dalam waktu yang sudah ditentukan, maka perselisihan dapat diselesaikan dengan mengikuti peraturan peraturan perundang-undangan terkait.</span></li>
                    <li><span style="font-family:Roboto;font-size:13.5pt;color:#494949;">Bahasa: Kebijakan Data Pribadi ini memungkinkan dibuat dalam bahasa lain diluar Bahasa Indonesia. Dalam hal terdapat ketidaksesuaian antara versi Bahasa Indonesia dengan bahasa lainnya, maka versi Bahasa Indonesia yang akan berlaku.</span></li>
                </ol>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">N. PERUBAHAN PADA KEBIJAKAN DATA PRIBADI</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Sportify.id dapat mengubah Kebijakan Data Pribadi ini dari waktu ke waktu dengan menampilkan versi yang telah diubah pada setiap dan/atau masing-masing Portal. Anda mengakui dan menyatakan bahwa Sportify.id dan/atau Afiliasinya memiliki hak untuk mengubah Kebijaka Data Pribadi ini secara sepihak dari waktu ke waktu oleh karena itu Anda menyatakan bahwa Anda secara seksama serta secara berkala memperhatikan dan membaca Kebijakan Data Pribadi ini. Dengan tetap mengakses Portal dan/atau keberlanjutan atas penggunaan setiap Layanan Sportify.id, maka Pelanggan dianggap telah memahami, tunduk dan menyetujui Kebijakan Data Pribadi ini berikut setiap perubahan-perubahannya.</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Apabila suatu bagian dari Kebijakan Data Pribadi tidak dapat dipakai/ berlaku, maka bagian tersebut tidak mempengaruhi keabsahan ketentuan lainnya.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;"><br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">O. HUBUNGI KAMI</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Jika anda mempunyai pertanyaan atau kepentingan atas Kebijakan Data Pribadi ini atau mengenai penggunaan Data Pribadi, hubungi Kami melalui:</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Jl. Kamper no 9 komp TNI AL RT 003 RW 006 Pondok labu, Jakarta Selatan DKI&nbsp;Jakarta&nbsp;12450</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Tel: 62-81 18771261<br>&nbsp;</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:18px;font-family:Roboto;color:#494949;padding:0cm;">P. TANGGAL EFEKTIF DAN LAIN-LAIN</span></strong></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kebijakan Data Pribadi ini terakhir dimutakhirkan dan diubah pada tanggal 1 Maret 2021. Dengan menggunakan Portal maupun Layanan Kami, Anda dianggap setuju atas Kebijakan Data Pribadi ini termasuk namun tidak terbatas pada seluruh perubahannya..</span></p>
                <p style='margin-top:2.25pt;margin-right:0cm;margin-bottom:11.25pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:18px;font-family:Roboto;color:#494949;">Kebijakan Data Pribadi ini tunduk dan ditafsirkan berdasarkan ketentuan hukum dan perundang-undangan yang berlaku di Indonesia.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-family:Roboto;">&nbsp;</span></p>
            </div>
            </div>
                </div>
                </div>   
                </div>
            </div>
        </div>
    </section>

@endsection